# Generated by Django 3.2.9 on 2021-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(default='oSCp3Nnc7a', max_length=10)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
