# Generated by Django 3.2.9 on 2021-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=80, unique=True)),
                ('senha', models.CharField(blank=True, max_length=8)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
